(eval-when-compile
  (require 'its)
  (require 'cl))

(eval-when (compile)
  (defconst its-compaction-enable t))

(defgroup greek nil
  "Greek Input Method"
  :group 'its)

(define-its-state-machine its-greek-jis-map
 "greek-jis" "Ω" Greek
 "Ελληνικα: Greek keyboard layout (JIS X0208.1983)

The layout is same as greek, but uses JIS characters.
Sorry, accents and terminal sigma are not supported in JIS."

 (its-defrule "1"  "１")
 (its-defrule "2"  "２")
 (its-defrule "3"  "３")
 (its-defrule "4"  "４")
 (its-defrule "5"  "５")
 (its-defrule "6"  "６")
 (its-defrule "7"  "７")
 (its-defrule "8"  "８")
 (its-defrule "9"  "９")
 (its-defrule "0"  "０")
 (its-defrule "-"  "−")
 (its-defrule "="  "＝")
 (its-defrule "`"  "‘")
 (its-defrule "q"  "・")
 (its-defrule "w"  "σ")
 (its-defrule "e"  "ε")
 (its-defrule "r"  "ρ")
 (its-defrule "t"  "τ")
 (its-defrule "y"  "υ")
 (its-defrule "u"  "θ")
 (its-defrule "i"  "ι")
 (its-defrule "o"  "ο")
 (its-defrule "p"  "π")
 (its-defrule "["  "［")
 (its-defrule "]"  "］")
 (its-defrule "a"  "α")
 (its-defrule "s"  "σ")
 (its-defrule "d"  "δ")
 (its-defrule "f"  "φ")
 (its-defrule "g"  "γ")
 (its-defrule "h"  "η")
 (its-defrule "j"  "ξ")
 (its-defrule "k"  "κ")
 (its-defrule "l"  "λ")
 (its-defrule ";"  "’")
 (its-defrule "'"  "’")
 (its-defrule "\\" "＼")
 (its-defrule "z"  "ζ")
 (its-defrule "x"  "χ")
 (its-defrule "c"  "ψ")
 (its-defrule "v"  "ω")
 (its-defrule "b"  "β")
 (its-defrule "n"  "ν")
 (its-defrule "m"  "μ")
 (its-defrule ","  ", ")
 (its-defrule "."  ". ")
 (its-defrule "/"  "／")
  
 (its-defrule "!"  "！")
 (its-defrule "@"  "＠")
 (its-defrule "#"  "＃")
 (its-defrule "$"  "＃")
 (its-defrule "%"  "％")
 (its-defrule "^"  "＾")
 (its-defrule "&"  "＆")
 (its-defrule "*"  "＊")
 (its-defrule "("  "（")
 (its-defrule ")"  "）")
 (its-defrule "_"  "＿")
 (its-defrule "+"  "＋")
 (its-defrule "~"  "￣")
 (its-defrule "Q"  "−")
 (its-defrule "W"  "Σ")
 (its-defrule "E"  "Ε")
 (its-defrule "R"  "Ρ")
 (its-defrule "T"  "Τ")
 (its-defrule "Y"  "Υ")
 (its-defrule "U"  "Θ")
 (its-defrule "I"  "Ι")
 (its-defrule "O"  "Ο")
 (its-defrule "P"  "Ρ")
 (its-defrule "{"  "｛")
 (its-defrule "}"  "｝")
 (its-defrule "A"  "Α")
 (its-defrule "S"  "Σ")
 (its-defrule "D"  "Δ")
 (its-defrule "F"  "Φ")
 (its-defrule "G"  "Γ")
 (its-defrule "H"  "Η")
 (its-defrule "J"  "Ξ")
 (its-defrule "K"  "Κ")
 (its-defrule "L"  "Λ")
 (its-defrule ":"  "”")
 (its-defrule "\"" "”")
 (its-defrule "|"  "｜")
 (its-defrule "Z"  "Ζ")
 (its-defrule "X"  "Χ")
 (its-defrule "C"  "Ψ")
 (its-defrule "V"  "Ω")
 (its-defrule "B"  "Β")
 (its-defrule "N"  "Ν")
 (its-defrule "M"  "Μ")
 (its-defrule "<"  "；")
 (its-defrule ">"  "：")
 (its-defrule "?"  "？"))

(define-its-state-machine its-greek-map
 "greek" "Ω" Greek
 "Ελληνικά: Greek keyboard layout (ISO 8859-7)
--------------

In the right of λ key is a combination key, where
 ΄ acute
 ¨ diaresis

e.g.
 α + ΄ -> ά
 ι + ¨ -> ϊ
 ι + ¨ + ΄ -> ΐ"

;; 1!  2@  3#  4$  5%  6^  7&  8*  9(  0)  -_  =+  `~
;;  ·―  ςΣ  εΕ  ρΡ  τΤ  υΥ  θΘ  ιΙ  οΟ  πΠ  [{  ]}
;;   αΑ  σΣ  δΔ  φΦ  γΓ  ηΗ  ξΞ  κΚ  λΛ  ΄¨  '"  \|
;;    ζΖ  χΧ  ψΨ  ωΩ  βΒ  νΝ  μΜ  ,;  .:  /?  

 (its-defrule "1"   "1")
 (its-defrule "2"   "2")
 (its-defrule "3"   "3")
 (its-defrule "4"   "4")
 (its-defrule "5"   "5")
 (its-defrule "6"   "6")
 (its-defrule "7"   "7")
 (its-defrule "8"   "8")
 (its-defrule "9"   "9")
 (its-defrule "0"   "0")
 (its-defrule "-"   "-")
 (its-defrule "="   "=")
 (its-defrule "`"   "`")
 (its-defrule "q"   "·")
 (its-defrule "w"   "ς")
 (its-defrule "e"   "ε")
 (its-defrule "r"   "ρ")
 (its-defrule "t"   "τ")
 (its-defrule "y"   "υ")
 (its-defrule "u"   "θ")
 (its-defrule "i"   "ι")
 (its-defrule "o"   "ο")
 (its-defrule "p"   "π")
 (its-defrule "["   "[")
 (its-defrule "]"   "]")
 (its-defrule "a"   "α")
 (its-defrule "s"   "σ")
 (its-defrule "d"   "δ")
 (its-defrule "f"   "φ")
 (its-defrule "g"   "γ")
 (its-defrule "h"   "η")
 (its-defrule "j"   "ξ")
 (its-defrule "k"   "κ")
 (its-defrule "l"   "λ")
 (its-defrule ";"   "΄")
 (its-defrule "'"   "'")
 (its-defrule "\\"  "\\")
 (its-defrule "z"   "ζ")
 (its-defrule "x"   "χ")
 (its-defrule "c"   "ψ")
 (its-defrule "v"   "ω")
 (its-defrule "b"   "β")
 (its-defrule "n"   "ν")
 (its-defrule "m"   "μ")
 (its-defrule ","   ",")
 (its-defrule "."   ".")
 (its-defrule "/"   "/")
 
 (its-defrule "!"   "!")
 (its-defrule "@"   "@")
 (its-defrule "#"   "#")
 (its-defrule "$"   "$")
 (its-defrule "%"   "%")
 (its-defrule "^"   "^")
 (its-defrule "&"   "&")
 (its-defrule "*"   "*")
 (its-defrule "("   "(")
 (its-defrule ")"   ")")
 (its-defrule "_"   "_")
 (its-defrule "+"   "+")
 (its-defrule "~"   "~")
 (its-defrule "Q"   "―")
 (its-defrule "W"   "Σ")
 (its-defrule "E"   "Ε")
 (its-defrule "R"   "Ρ")
 (its-defrule "T"   "Τ")
 (its-defrule "Y"   "Υ")
 (its-defrule "U"   "Θ")
 (its-defrule "I"   "Ι")
 (its-defrule "O"   "Ο")
 (its-defrule "P"   "Π")
 (its-defrule "{"   "{")
 (its-defrule "}"   "}")
 (its-defrule "A"   "Α")
 (its-defrule "S"   "Σ")
 (its-defrule "D"   "Δ")
 (its-defrule "F"   "Φ")
 (its-defrule "G"   "Γ")
 (its-defrule "H"   "Η")
 (its-defrule "J"   "Ξ")
 (its-defrule "K"   "Κ")
 (its-defrule "L"   "Λ")
 (its-defrule ":"   "¨")
 (its-defrule "\""  "\"")
 (its-defrule "|"   "|")
 (its-defrule "Z"   "Ζ")
 (its-defrule "X"   "Χ")
 (its-defrule "C"   "Ψ")
 (its-defrule "V"   "Ω")
 (its-defrule "B"   "Β")
 (its-defrule "N"   "Ν")
 (its-defrule "M"   "Μ")
 (its-defrule "<"   ";")
 (its-defrule ">"   ":")
 (its-defrule "?"   "?")
 
 (its-defrule "a;"  "ά")
 (its-defrule "e;"  "έ")
 (its-defrule "h;"  "ή")
 (its-defrule "i;"  "ί")
 (its-defrule "o;"  "ό")
 (its-defrule "y;"  "ύ")
 (its-defrule "v;"  "ώ")
 (its-defrule "A;"  "Ά")
 (its-defrule "E;"  "Έ")
 (its-defrule "H;"  "Ή")
 (its-defrule "I;"  "Ί")
 (its-defrule "O;"  "Ό")
 (its-defrule "Y;"  "Ύ")
 (its-defrule "V;"  "Ώ")
 (its-defrule "i:"  "ϊ")
 (its-defrule "y:"  "ϋ")
 (its-defrule "I:"  "Ϊ")
 (its-defrule "Y:"  "Ϋ")
 (its-defrule "i:;" "ΐ")
 (its-defrule "y:;" "ΰ"))

(provide 'its/greek)
